const REGISTER = 'REGISTER'
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const SET_USER = 'SET_USER'
const SET_USER_FROM_LOCAL = 'SET_USER_FROM_LOCAL'

export {
  SET_USER,
  REGISTER,
  LOGIN,
  LOGOUT,
  SET_USER_FROM_LOCAL
}
